version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
    - postgres_volume:/var/lib/postgresql/data
    restart: always
  web: &app
    build: .
    command: /bin/sh -c "rm -f /src/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - db
  webpacker:
    <<: *app
    depends_on:
      - web
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: /bin/sh -c "bin/webpack-dev-server"
    volumes:
      - ./src:/app
      - ./src/node_modules:/app/node_modules
    ports:
      - "3035:3035"
volumes:
  postgres_volume:
